builds:
  - binary: kibble
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    ldflags: -s -w -X kibble/version.Version={{.Version}}
    hooks:
      post: sh ./deploy_aws.sh {{.Version}} {{.Os}}

archives:
- id: main
  format: tar.gz
  replacements:
    amd64: 64-bit
    darwin: macOS
    linux: Tux
  format_overrides:
    - goos: windows
      format: zip
    - goos: darwin
      format: zip

changelog:
  filters:
    exclude:
      - '^docs:'
      - typo
      - (?i)foo

release:
  github:
    owner: shift72
    name: kibble

blobs:
  -
    provider: s3
    bucket: shift72-sites
    region: ap-southeast-2
    folder: "s72-web/kibble/{{.Version}}"
